version: '3.1'

services:
  joomla:
    image: joomla:latest
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: mariadb
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    volumes:
      - joomla_data:/var/www/html
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    volumes:
      - db_data:/var/lib/mysql

volumes:
  joomla_data:
  db_data:
